---
- name: enable web server
  hosts: ansible1
  tasks:
  - name: install stuff
    yum:
    - httpd
    - firewalld
  - name: create a welcome page
    copy:
      content: "welcome to the webserver\n"
      dest: /var/www/html/index.html
  - name: enable webserver
    service: 
      name: httpd
      state: started
      enabled: true
  - name: enable firewall
    service:
      name: firewalld
      state: started
      enabled: true
  - name: open service in firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

- name: test webserver access
  hosts: localhost
  become: no
  tasks:
  - name: test webserver access
    uri:
      url: http://ansible1
      return_content: yes
      status_code: 200

