---
- name: create a user using a variable
  hosts: ansible1
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }} on host {{ ansible_hostname }} 
      user:
        name: "{{ user }}"
